version: '3'

services:

  nodejs-api:
    build:
      context: ./AccountBlockerNodeApi
      dockerfile: Dockerfile
    ports:
       - '3000:3000'
    restart: always  
    container_name: node-api
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - ./AccountBlockerNodeApi/:/usr/src/app
    links:
      - mongodb 
      - redis:redis  
                    
  nodejs-socket:
    build:
      context: ./AccountBlockerSocket
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: node-socket
    environment:
       - REDIS_URL=redis://cache
    volumes:
      - ./AccountBlockerSocket/:/usr/src/app
    links:  
      - redis:redis
              
  angular-web:
    build:
      context: ./AccountBlockerWeb
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
      - ./AccountBlockerWeb/:/app
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db  

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379  
    
volumes:
  data:   
