version: '3'
services:
  nodejs-api:
    build:
      context: ./AccountBlockerNodeApi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
      - ./AccountBlockerNodeApi/:/var/www/app
    links:
      - mongogb 
       
       
  nodejs-socket:
    build:
      context: ./AccountBlockerSocket
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: node-socket
    volumes:
      - ./AccountBlockerSocket/:/var/www/app
        
       
  angular-web:
    build:
      context: ./AccountBlockerWeb
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
      - ./AccountBlockerWeb/:/var/www/app
    
  mongogb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/AccountBlocker
    

volumes:
  data:     